---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: spring-boot
  name: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - image: gcr.io/rugged-precept-258803/spring-boot-container-test:latest
        imagePullPolicy: Always
        name: spring-boot

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot
  labels:
    app: spring-boot
spec:
  ports:
    - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot
  type: LoadBalancer
